### ISSUE TITLE
不支持Mac吗?

### ISSUE THREAD

**Issue by LanYunDev** [hitczw/automatic-sokoban-solver#1]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/95263282/168441183-56d7793d-7822-4316-8ff9-60b16673fbb7.png">
➜  sokoban_project git:(master) cd build/
➜  build git:(master) cmake ..
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/build
➜  build git:(master) ✗ make
[ 10%] Building CXX object CMakeFiles/soboban_solver.dir/src/constant.cpp.o
In file included from /Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:1:
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/include/constant.h:10:37: error: a space is required between consecutive right angle brackets (use '> >')
        extern std::vector<std::vector<char>> blank_matrix;
                                           ^~
                                           > >
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/include/constant.h:11:37: error: a space is required between consecutive right angle brackets (use '> >')
        extern std::vector<std::vector<bool>> end_vec;
                                           ^~
                                           > >
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/include/constant.h:12:37: error: a space is required between consecutive right angle brackets (use '> >')
        extern std::vector<std::vector<bool>> matrix0;
                                           ^~
                                           > >
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:6:45: error: non-aggregate type 'const point' cannot be initialized with an initializer list
const point constant::four_direction[4] = { {0,1},{1,0},{0,-1},{-1,0} };
                                            ^~~~~
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:6:51: error: non-aggregate type 'const point' cannot be initialized with an initializer list
const point constant::four_direction[4] = { {0,1},{1,0},{0,-1},{-1,0} };
                                                  ^~~~~
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:6:57: error: non-aggregate type 'const point' cannot be initialized with an initializer list
const point constant::four_direction[4] = { {0,1},{1,0},{0,-1},{-1,0} };
                                                        ^~~~~~
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:6:64: error: non-aggregate type 'const point' cannot be initialized with an initializer list
const point constant::four_direction[4] = { {0,1},{1,0},{0,-1},{-1,0} };
                                                               ^~~~~~
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:7:19: error: a space is required between consecutive right angle brackets (use '> >')
vector<vector<char>> constant::blank_matrix;
                  ^~
                  > >
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:8:19: error: a space is required between consecutive right angle brackets (use '> >')
vector<vector<bool>> constant::end_vec;
                  ^~
                  > >
/Users/lanyun/Downloads/automatic-sokoban-solver/sokoban_project/src/constant.cpp:9:19: error: a space is required between consecutive right angle brackets (use '> >')
vector<vector<bool>> constant::matrix0;
                  ^~
                  > >
10 errors generated.
make[2]: *** [CMakeFiles/soboban_solver.dir/src/constant.cpp.o] Error 1
make[1]: *** [CMakeFiles/soboban_solver.dir/all] Error 2
make: *** [all] Error 2

<img width="730" alt="image" src="https://user-images.githubusercontent.com/95263282/168441196-9bb1d5bf-e2b7-4495-a990-c779ed4185cc.png">

**Comment by hitczw** [comment]
可能是编译器的原因，没有用过clang编译过，搜索了相关的问题链接，可能对你有帮助
https://www.icode9.com/content-4-368430.html
